# Generated by Django 4.2.3 on 2023-07-11 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_addr', models.GenericIPAddressField()),
                ('user_agent', models.CharField(max_length=200)),
                ('visit_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linked_url', models.URLField()),
                ('shortened_code', models.CharField(max_length=100, unique=True)),
                ('creation_time', models.DateTimeField(auto_now=True)),
                ('qr_code', models.CharField(max_length=500)),
                ('is_password_protected', models.BooleanField()),
                ('can_expire', models.BooleanField()),
                ('password', models.CharField(blank=True, max_length=100)),
                ('expiration_time', models.DateTimeField(blank=True)),
                ('visitors', models.ManyToManyField(blank=True, to='urlapp.visitor')),
            ],
        ),
    ]
